const db = [
  {
    url: "./assets/images/1_mercury.png",
    id: "mercure",
    name: "Mercure",
    englishName: "Mercury",
    isPlanet: true,
    isMoon: false,
    bodyType: "Planet",
    placement: 1,
    curiosites: {
      "short-description": [
        "Distance par rapport au Soleil : 46 001 200 à 69 816 900 kilomètres",
        "Température de surface moyenne : 117° C",
        "Temps de voyage spatial depuis la Terre : 4 ans",
        "Gravité : Si tu pèses 45 kilogrammes sur Terre, tu pèseras 17 kilogrammes sur Mercure.",
        "Mercure est une planète des extrêmes. La nuit, les températures chutent de plusieurs centaines de degrés sous le point de congélation.",
        "Quand il fait 30° C sur Terre, il fait 240° C sur Vénus !",
        "La température moyenne de Vénus est plus de huit fois supérieure à celle mesurée à l'endroit le plus chaud sur Terre.",
        "Vénus a à peu près la même taille et la même densité que la Terre. Comme la Terre, elle a des nuages et du vent.",
        "Vénus est la planète qui a le plus de volcan !",
      ],
      "long-description": [
        "Mercure est une planète des extrêmes. Le jour (qui dure environ 30 jours terrestres), c'est l'un des endroits les plus chauds du système solaire - plus de quatre fois plus chaud que l'eau bouillante.",
        "Celle que nous surnommons l'« étoile du Berger » n'est pas une étoile, mais bien une planète. Il s'agit de Vénus. Deuxième planète du système solaire par ordre d'éloignement au Soleil, elle doit son nom à la déesse romaine de l'Amour. Sur Vénus, une journée dure plus longtemps qu'une année, le soleil se lève à l'ouest et se couche à l'est, et il y fait toujours chaud, très chaud !",
        "Sur Vénus, il y a plus de 1600 volcans, et la plupart d'entre eux sont endormis. Ainsi, elle est la planète du système solaire qui en a le plus !",
      ],
    },
    moons: null,
    gravity: 3.7,
    gazeuse: false,
    naine: false,
    tellurique: true,
    aroundPlanet: null,
    discoveredBy: "",
    discoveryDate: "",
  },
  {
    url: "./assets/images/1_mercury.png",
    id: "venus",
    name: "Vénus",
    englishName: "Venus",
    isPlanet: true,
    isMoon: false,
    bodyType: "Planet",
    placement: 2,
    curiosites: {
      "short-description": [
        "Distance par rapport au Soleil : 46 001 200 à 69 816 900 kilomètres",
        "Température de surface moyenne : 117° C",
        "Temps de voyage spatial depuis la Terre : 4 ans",
        "Gravité : Si tu pèses 45 kilogrammes sur Terre, tu pèseras 17 kilogrammes sur Mercure.",
        "Mercure est une planète des extrêmes. La nuit, les températures chutent de plusieurs centaines de degrés sous le point de congélation.",
        "Quand il fait 30° C sur Terre, il fait 240° C sur Vénus !",
        "La température moyenne de Vénus est plus de huit fois supérieure à celle mesurée à l'endroit le plus chaud sur Terre.",
        "Vénus a à peu près la même taille et la même densité que la Terre. Comme la Terre, elle a des nuages et du vent.",
        "Vénus est la planète qui a le plus de volcan !",
      ],
      "long-description": [
        "Mercure est une planète des extrêmes. Le jour (qui dure environ 30 jours terrestres), c'est l'un des endroits les plus chauds du système solaire - plus de quatre fois plus chaud que l'eau bouillante.",
        "Celle que nous surnommons l'« étoile du Berger » n'est pas une étoile, mais bien une planète. Il s'agit de Vénus. Deuxième planète du système solaire par ordre d'éloignement au Soleil, elle doit son nom à la déesse romaine de l'Amour. Sur Vénus, une journée dure plus longtemps qu'une année, le soleil se lève à l'ouest et se couche à l'est, et il y fait toujours chaud, très chaud !",
        "Sur Vénus, il y a plus de 1600 volcans, et la plupart d'entre eux sont endormis. Ainsi, elle est la planète du système solaire qui en a le plus !",
      ],
    },
    moons: null,
    gravity: 8.87,
    gazeuse: false,
    naine: false,
    tellurique: true,
    aroundPlanet: null,
    discoveredBy: "",
    discoveryDate: "",
  },
  {
    url: "./assets/images/2_venus.png",
    id: "terre",
    name: "La Terre",
    englishName: "Earth",
    isPlanet: true,
    isMoon: false,
    bodyType: "Planet",
    placement: "3 planète à partir du Soleil",
    curiosites: {
      "short-description": [],
      "long-description": [],
    },
    moons: ["La Lune"],
    gravity: 9.8,
    gazeuse: false,
    naine: false,
    tellurique: true,
    aroundPlanet: null,
    discoveredBy: "",
    discoveryDate: "",
  },
  {
    url: "./assets/images/1_mercury.png",
    id: "La Lune",
    name: "La Lune",
    englishName: "Moon",
    isPlanet: false,
    isMoon: true,
    bodyType: "moon",
    placement: null,
    curiosites: {
      "short-description": [],
      "long-description": [],
    },
    moons: null,
    gravity: "",
    gazeuse: false,
    naine: false,
    tellurique: true,
    aroundPlanet: "Terre",
    discoveredBy: "",
    discoveryDate: "",
  },
];
